Vietnamese translations
spekulatius/PHPScraper pull request #104
Opened 2022-09-16 08:25 UTC by datlechin

2022-09-17 12:18 UTC, datlechin commented
you can merge this PR, I'll continue to translate in the next PRs

2022-09-18 09:40 UTC, spekulatius requested changes
Hey @datlechin,

Thank you for your PR! There are a few more places with English. To make it easier I've added some parts for review.

Cheers,
Peter

2022-09-18 09:40 UTC, spekulatius commented on websites/vi/examples/extract-keywords.md
> +While scraping content is often enough, sometimes you require to extract significant terms and phrases (keywords) from this content. PHPScraper allows you to extract the keywords of the website direc
Still English :)

2022-09-18 09:40 UTC, spekulatius commented on websites/vi/examples/extract-keywords.md
> +// Navigate to the test page.
This can stay in English I think

2022-09-18 09:40 UTC, spekulatius commented on websites/vi/examples/extract-keywords.md
> +The default language (locale) for this is `en_US`. Other languages can be passed as a parameter. This currently works only for a selection of languages. Check this [list](https://github.com/Donatello
These sections could be translated too

2022-09-18 09:40 UTC, spekulatius commented on websites/vi/examples/headings.md
> +Scraping a single heading is easy and be done following this example:
This could be translated too

2022-09-18 09:40 UTC, spekulatius commented on websites/vi/examples/lists.md
> +Scraping lists follows a similar approach as other scraping with PHPScraper:
We can translate the heading and the actual content here too :)

2022-09-18 09:40 UTC, spekulatius commented on websites/vi/examples/navigation.md
> +# Navigation
We can translate the heading and the actual content here too :)

2022-09-18 09:40 UTC, spekulatius commented on websites/vi/examples/paragraphs.md
> + * - Maecenas eget ex sit amet urna porta fermentum at ut dui. Praesent lectus arcu, hendrerit sed mi vel, commodo lacinia velit. Nullam ac velit quis ante tristique scelerisque quis non metus. Pelle
This should stay as it is this way in the test pages

2022-09-18 09:40 UTC, spekulatius commented on websites/vi/examples/scrape-header-tags.md
> +# Thu thập thẻ Header
:+1:

2022-09-18 09:40 UTC, spekulatius commented on websites/vi/examples/scrape-links.md
> +The scraping of links works very similar to [image scraping](/examples/scrape-images.html). You can retrieve a list of URL without any additional information as well as a detailed list containing `re
This could be translated too :)

2022-09-18 09:40 UTC, spekulatius commented on websites/vi/examples/scrape-social-media-meta-tags.md
> +Scraping social media sharing tags from a website can be done using the following methods. The exact result set depends on the provided tags. All tags are included, as long as these are in the prefix
We can translate the heading and the actual content here too :)

2022-09-18 09:40 UTC, spekulatius commented on websites/vi/examples/scrape-website-title.md
> +# Thu thập tiêu đề trang web
:star_struck:

2022-09-19 21:04 UTC, spekulatius requested changes
Awesome work @datlechin, could you check these two points?

2022-09-19 21:04 UTC, spekulatius commented on websites/vi/examples/scrape-links.md
> + * Navigate to the test page. It contains 6 links to placekitten.com with different attributes:
Should we translate this too @datlechin ?

2022-09-19 21:04 UTC, spekulatius commented on websites/vi/examples/scrape-social-media-meta-tags.md
> +Thu thập các thẻ meta chia sẻ mạng xã hội từ trang web bằng các phương thức sau. Kết quả phụ thuộc vào thẻ được cung cấp. Tất cả các thẻ đều được bao gồm, miễn là chúng nằm trong không gian tên có ti
I think this needs a closing ` @datlechin

2022-09-20 06:36 UTC, spekulatius commented
Hey @datlechin 

looks pretty good!

I've [updated some parts](https://github.com/spekulatius/PHPScraper/tree/master/websites/misc) and [mentioned your project](https://github.com/spekulatius/PHPScraper/blob/master/websites/misc/show-case.md) too!

Should we merge this and continue on a new PR with the remain pages?

Cheers,
Peter

2022-09-20 07:30 UTC, datlechin commented
I've finished translate `misc` folder.

2022-09-20 07:44 UTC, spekulatius requested changes

2022-09-20 07:44 UTC, spekulatius commented on websites/vi/README.md
> +The code is roughly covered with end-to-end tests. For this, simple web-pages are hosted under *https://test-pages.phpscraper.de/*, loaded and parsed using [PHPUnit](https://phpunit.de/). These tests
We still have some English here @datlechin

2022-09-20 07:44 UTC, spekulatius commented on websites/.vuepress/config.theme.vi.js
> +                'examples/scrape-website-title',
Can you prefix the folder for the pages? For example `examples/scrape-website-title` will be `vi/examples/scrape-website-title`. Thank you!

2022-09-20 08:15 UTC, spekulatius commented on websites/vi/examples/scrape-header-tags.md
> +Xem thêm thông tin về cách lấy [thẻ meta](/examples/scrape-meta-tags.html).
Can you search for internal links like this one and prefix them with `vi/` too? Currently they go back to the English site

Thank you @datlechin. I think with this we should be ready to go-live :star_struck:

2022-09-20 09:58 UTC, spekulatius approved these changes

2022-09-20 09:59 UTC, merged

2022-09-20 10:00 UTC, spekulatius commented
Thank you so much for translating the website :star_struck: Awesome work @datlechin!